# Global parameters
baseURL = "https://antiz.fr/"
languageCode = "en-us"
title = "Robin Candau"
theme = "anatole" 
enableEmoji = true
summaryLength = 50

# Site parameters
[params]
	title = "Robin Candau"
	author = "Robin Candau"
	description = "Linux system & DevOps engineer passionate about skateboarding, music, cycling and, obviously, Linux!"
	profilePicture = "images/pfp.jpg"
	contentratio = 0.7
	customCss = ["css/custom.css"]
	mainSections = []
	postSectionName = "blog"

	[[params.socialIcons]]
	icon = "fab fa-github"
	title = "GitHub"
	url = "https://github.com/Antiz96"

	[[params.socialIcons]]
	icon = "fab fa-gitlab"
	title = "Arch Linux GitLab"
	url = "https://gitlab.archlinux.org/antiz"

	[[params.socialIcons]]
	icon = "fab fa-mastodon"
	title = "Mastodon"
	url = "https://fosstodon.org/@Antiz"

	[[params.socialIcons]]
	icon = "fab fa-linkedin"
	title = "LinkedIn"
	url = "https://www.linkedin.com/in/robin-candau/?locale=en_US"

	[[params.socialIcons]]
	icon = "fas fa-envelope"
	title = "Mail"
	url = "mailto:robincandau@protonmail.com"

	[[params.socialIcons]]
	icon = "fas fa-key"
	title = "OpenPGP Key"
	url = "https://keyserver.ubuntu.com/pks/lookup?search=D33FAA16B937F3B2&fingerprint=on&op=index"

[menu]
	[[menu.main]]
	name = "Home"
	identifier = "home"
	weight = 100
	url = "/"

	[[menu.main]]
	name = "Blog"
	identifier = "blog"
	weight = 200
	url = "/blog/"

