name: Build Website
on: pull_request

permissions:
  contents: write

jobs:
  build_website:
    runs-on: ubuntu-latest

    container:
      image: docker.io/library/alpine:latest
      options: --privileged

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Update container
        run: apk update && apk upgrade

      - name: Install packages
        run: apk add git hugo

      - name: Build website
        run: cd antiz && hugo

      - name: Commit website
        run: |
          pwd && ls -ltrA
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Automated build"
          git push
