name: Build website
on: pull_request

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  test_suite:
    runs-on: ubuntu-latest

    container:
      image: docker.io/library/alpine:latest
      options: --privileged

    steps:
      - name: Update container
        run: apk update && apk upgrade

      - name: Install packages
        run: apk add git hugo

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Build website
        run: pwd && ls -ltrA && git branch

#      - name: Configure git
#        run: |
#          cd $REPO_NAME
#          git config --local user.email "actions@github.com"
#          git config --local user.name "GitHub Actions"

#      - name: Commit and push
#        run: |
#          cd $REPO_NAME
#          git add .
#          git commit -m "Automatic build"
#          git push
