name: CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Build:
    if: github.event_name == 'pull_request'
    runs-on:
      - self-hosted
      - CI-CD

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.BUILD_WEBSITE_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Init theme submodule
        run: git submodule update --init

      - name: Copy custom CSS in theme
        run: cp custom.css themes/anatole/assets/css/custom.css 

      - name: Build website
        run: rm -rf public && hugo

      - name: Commit automated build
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [ "$(git status --porcelain public)" ]; then
                  git add public
                  git commit -m "Automated build"
                  git push
          else
                  echo "No changes to commit"
          fi

  Deploy:
    runs-on:
      - self-hosted
      - CI-CD

      - name: Deploy website
        run: |
          if [ "$(git rev-parse --abbrev-ref HEAD)" == "dev" ]; then
                  /opt/github-runner/antiz.fr/deploy_website.sh dev
          elif [ "$(git rev-parse --abbrev-ref HEAD)" == "main" ]; then
                  /opt/github-runner/antiz.fr/deploy_website.sh prod
          else
                  echo "Invalid branch, make sure you opened your pull request from the 'dev' branch"
                  exit 1
          fi
