name: CD
on: pull_request

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.BUILD_WEBSITE_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install packages
        run: sudo apt install hugo

      - name: Build website
        run: rm -rf public && hugo

      - name: Commit automated build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automated build"
          git push
