name: CD
on: pull_request

jobs:
  Build:
    runs-on: ubuntu-latest

    container:
      image: docker.io/library/alpine:latest
      options: --privileged

    steps:
      - name: Update container
        run: apk update && apk upgrade

      - name: Install packages
        run: apk add git hugo

      - name: Clone repo
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.BUILD_WEBSITE_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build website
        run: rm -rf public && hugo

      - name: Commit automated build
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [ "$(git status --porcelain)" ]; then
                  git add .
                  git commit -m "Automated build"
                  git push
          else
                  echo "No changes to commit"
          fi
